// Package desktop generates the per-account Claude Desktop launcher and its
// application-menu entry.
//
// Each account gets its own Electron --user-data-dir, which is what lets two
// instances run side by side with separate logins, and its own
// CLAUDE_CONFIG_DIR, which is what makes the Code tab inside that window use
// the matching CLI account.
//
// The launcher is the same shell script on both platforms; only the menu entry
// differs -- a .desktop file on Linux, an .app bundle on macOS. Both are just
// files, so which one gets written is decided from the Layout at run time
// rather than by a build constraint: that way the macOS bundle can be
// generated and checked from a Linux test.
package desktop

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"claude-profile/internal/fsx"
	"claude-profile/internal/paths"
	"claude-profile/internal/profile"
)

const shimTemplate = `#!/usr/bin/env bash
# Claude Desktop -- %s instance. Generated by claude-profile; edits are lost on
# the next 'claude-profile add/rename'. Own Electron user-data-dir (separate
# login and window, runs alongside the other accounts) and own
# CLAUDE_CONFIG_DIR for its Code tab.
exec claude-profile desktop %s "$@"
`

const entryTemplate = `[Desktop Entry]
Name=Claude (%s)
Comment=Claude Desktop — %s
GenericName=AI Assistant
Keywords=AI;Chat;Assistant;Claude;Code;LLM;%s;
Exec=%s %%U
Icon=claude-desktop
Type=Application
StartupNotify=true
StartupWMClass=claude-desktop-%s
Categories=Utility;Development;
`

// plistTemplate is the smallest bundle macOS will treat as an application.
// CFBundleName is what the Dock and Spotlight show, so the label lands there;
// the identifier is per-profile so that two instances are distinct apps and
// macOS does not fold their windows together.
const plistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>Claude (%s)</string>
	<key>CFBundleDisplayName</key>
	<string>Claude (%s)</string>
	<key>CFBundleIdentifier</key>
	<string>com.aymenkrifa.claude-profile.%s</string>
	<key>CFBundleExecutable</key>
	<string>%s</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.developer-tools</string>
	<key>NSHighResolutionCapable</key>
	<true/>
</dict>
</plist>
`

// Install writes the launcher shim and the application-menu entry.
func Install(l paths.Layout, p *profile.Profile) error {
	shim := l.Shim(p.Name)
	if err := os.MkdirAll(filepath.Dir(shim), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(shim, []byte(fmt.Sprintf(shimTemplate, p.Title(), p.Name)), 0o755); err != nil {
		return err
	}
	comment := p.Label
	if comment == "" {
		comment = p.Name + " account"
	}
	if l.Darwin() {
		return installBundle(l, p, comment)
	}
	return installDesktopEntry(l, p, comment, shim)
}

// installDesktopEntry writes the freedesktop.org menu entry.
func installDesktopEntry(l paths.Layout, p *profile.Profile, comment, shim string) error {
	entry := l.DesktopEntry(p.Name)
	if err := os.MkdirAll(filepath.Dir(entry), 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf(entryTemplate, p.Title(), comment, p.Title(), shim, p.Name)
	if err := os.WriteFile(entry, []byte(body), 0o644); err != nil {
		return err
	}
	refresh(l)
	return nil
}

// installBundle writes the .app wrapper macOS needs to show the account in
// Spotlight and the Dock. Its executable only re-enters this tool, so the
// launch flags live in exactly one place, the same as the Linux shim.
func installBundle(l paths.Layout, p *profile.Profile, comment string) error {
	bundle := l.DesktopEntry(p.Name)
	exe := "claude-" + p.Name
	macos := filepath.Join(bundle, "Contents", "MacOS")
	if err := os.MkdirAll(macos, 0o755); err != nil {
		return err
	}
	plist := fmt.Sprintf(plistTemplate, p.Title(), p.Title(), p.Name, exe)
	if err := os.WriteFile(filepath.Join(bundle, "Contents", "Info.plist"), []byte(plist), 0o644); err != nil {
		return err
	}
	launcher := fmt.Sprintf(`#!/usr/bin/env bash
# Claude Desktop -- %s instance (%s). Generated by claude-profile; edits are
# lost on the next 'claude-profile add/rename'.
exec claude-profile desktop %s "$@"
`, p.Title(), comment, p.Name)
	if err := os.WriteFile(filepath.Join(macos, exe), []byte(launcher), 0o755); err != nil {
		return err
	}
	refresh(l)
	return nil
}

// Remove deletes a profile's launcher and menu entry. The macOS entry is a
// directory, so this has to recurse; RemoveAll covers the Linux file too.
func Remove(l paths.Layout, name string) error {
	if err := os.Remove(l.Shim(name)); err != nil && !os.IsNotExist(err) {
		return err
	}
	if err := os.RemoveAll(l.DesktopEntry(name)); err != nil {
		return err
	}
	refresh(l)
	return nil
}

// Installed reports whether the menu entry exists.
func Installed(l paths.Layout, name string) bool {
	return fsx.Exists(l.DesktopEntry(name))
}

// refresh asks the desktop environment to re-read the menu. Best effort: on
// Linux a missing update-desktop-database only means the entry appears a bit
// later, and on macOS Launch Services notices a new bundle on its own.
func refresh(l paths.Layout) {
	if l.Darwin() {
		return
	}
	if bin, err := exec.LookPath("update-desktop-database"); err == nil {
		_ = exec.Command(bin, l.AppsDir()).Run()
	}
}
