// Package desktop generates the per-account Claude Desktop launcher and its
// application-menu entry.
//
// Each account gets its own Electron --user-data-dir, which is what lets two
// instances run side by side with separate logins, and its own
// CLAUDE_CONFIG_DIR, which is what makes the Code tab inside that window use
// the matching CLI account.
package desktop

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"claude-profile/internal/fsx"
	"claude-profile/internal/paths"
	"claude-profile/internal/profile"
)

const shimTemplate = `#!/usr/bin/env bash
# Claude Desktop -- %s instance. Generated by claude-profile; edits are lost on
# the next 'claude-profile add/rename'. Own Electron user-data-dir (separate
# login and window, runs alongside the other accounts) and own
# CLAUDE_CONFIG_DIR for its Code tab.
exec claude-profile desktop %s "$@"
`

const entryTemplate = `[Desktop Entry]
Name=Claude (%s)
Comment=Claude Desktop — %s
GenericName=AI Assistant
Keywords=AI;Chat;Assistant;Claude;Code;LLM;%s;
Exec=%s %%U
Icon=claude-desktop
Type=Application
StartupNotify=true
StartupWMClass=claude-desktop-%s
Categories=Utility;Development;
`

// Install writes the launcher shim and .desktop entry for a profile.
func Install(l paths.Layout, p *profile.Profile) error {
	shim := l.Shim(p.Name)
	if err := os.MkdirAll(filepath.Dir(shim), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(shim, []byte(fmt.Sprintf(shimTemplate, p.Title(), p.Name)), 0o755); err != nil {
		return err
	}
	comment := p.Label
	if comment == "" {
		comment = p.Name + " account"
	}
	entry := l.DesktopEntry(p.Name)
	if err := os.MkdirAll(filepath.Dir(entry), 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf(entryTemplate, p.Title(), comment, p.Title(), shim, p.Name)
	if err := os.WriteFile(entry, []byte(body), 0o644); err != nil {
		return err
	}
	refresh(l)
	return nil
}

// Remove deletes a profile's launcher and menu entry.
func Remove(l paths.Layout, name string) error {
	for _, f := range []string{l.Shim(name), l.DesktopEntry(name)} {
		if err := os.Remove(f); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	refresh(l)
	return nil
}

// Installed reports whether the menu entry exists.
func Installed(l paths.Layout, name string) bool {
	return fsx.Exists(l.DesktopEntry(name))
}

// refresh asks the desktop environment to re-read the menu. Best effort: a
// missing update-desktop-database only means the entry appears a bit later.
func refresh(l paths.Layout) {
	if bin, err := exec.LookPath("update-desktop-database"); err == nil {
		_ = exec.Command(bin, l.AppsDir()).Run()
	}
}
